"""update order unique

Revision ID: 0bde1fd12bb3
Revises: 7a7f1631c632
Create Date: 2025-12-30 15:22:27.403981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bde1fd12bb3'
down_revision: Union[str, Sequence[str], None] = '7a7f1631c632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ref_provinces_ProvinceId'), table_name='ref_provinces')
    op.drop_index(op.f('ix_ref_provinces_ProvinceNameEN'), table_name='ref_provinces')
    op.drop_index(op.f('ix_ref_provinces_ProvinceNameTH'), table_name='ref_provinces')
    op.drop_table('ref_provinces')
    op.drop_index(op.f('ix_ref_zone_ZoneId'), table_name='ref_zone')
    op.drop_index(op.f('ix_ref_zone_ZoneNameEN'), table_name='ref_zone')
    op.drop_index(op.f('ix_ref_zone_ZoneNameTH'), table_name='ref_zone')
    op.drop_table('ref_zone')
    op.drop_index(op.f('ix_promotions_promocode'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_order_email'), table_name='order')
    op.create_index(op.f('ix_order_email'), 'order', ['email'], unique=False)
    op.drop_index(op.f('ix_order_first_name_customer'), table_name='order')
    op.create_index(op.f('ix_order_first_name_customer'), 'order', ['first_name_customer'], unique=False)
    op.drop_index(op.f('ix_order_last_name_customer'), table_name='order')
    op.create_index(op.f('ix_order_last_name_customer'), 'order', ['last_name_customer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_last_name_customer'), table_name='order')
    op.create_index(op.f('ix_order_last_name_customer'), 'order', ['last_name_customer'], unique=True)
    op.drop_index(op.f('ix_order_first_name_customer'), table_name='order')
    op.create_index(op.f('ix_order_first_name_customer'), 'order', ['first_name_customer'], unique=True)
    op.drop_index(op.f('ix_order_email'), table_name='order')
    op.create_index(op.f('ix_order_email'), 'order', ['email'], unique=True)
    op.create_table('promotions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('promocode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('promotion_title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('discount', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('promotions_pkey'))
    )
    op.create_index(op.f('ix_promotions_promocode'), 'promotions', ['promocode'], unique=False)
    op.create_table('ref_zone',
    sa.Column('ZoneId', sa.INTEGER(), server_default=sa.text('nextval(\'"ref_zone_ZoneId_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('ZoneNameTH', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ZoneNameEN', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ZoneId', name='ref_zone_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_ref_zone_ZoneNameTH'), 'ref_zone', ['ZoneNameTH'], unique=False)
    op.create_index(op.f('ix_ref_zone_ZoneNameEN'), 'ref_zone', ['ZoneNameEN'], unique=False)
    op.create_index(op.f('ix_ref_zone_ZoneId'), 'ref_zone', ['ZoneId'], unique=False)
    op.create_table('ref_provinces',
    sa.Column('ProvinceId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ProvinceNameTH', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ProvinceNameEN', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ZoneId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ZoneId'], ['ref_zone.ZoneId'], name=op.f('ref_provinces_ZoneId_fkey')),
    sa.PrimaryKeyConstraint('ProvinceId', name=op.f('ref_provinces_pkey'))
    )
    op.create_index(op.f('ix_ref_provinces_ProvinceNameTH'), 'ref_provinces', ['ProvinceNameTH'], unique=False)
    op.create_index(op.f('ix_ref_provinces_ProvinceNameEN'), 'ref_provinces', ['ProvinceNameEN'], unique=False)
    op.create_index(op.f('ix_ref_provinces_ProvinceId'), 'ref_provinces', ['ProvinceId'], unique=False)
    # ### end Alembic commands ###
