"""Initial

Revision ID: 7277178ccd56
Revises: 
Create Date: 2025-12-14 17:03:39.137619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7277178ccd56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_home_page',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('note', sa.String(length=150), nullable=True),
    sa.Column('img_path', sa.String(length=150), nullable=True),
    sa.Column('link', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_home_page_created_by'), 'blog_home_page', ['created_by'], unique=False)
    op.create_index(op.f('ix_blog_home_page_id'), 'blog_home_page', ['id'], unique=False)
    op.create_index(op.f('ix_blog_home_page_is_active'), 'blog_home_page', ['is_active'], unique=False)
    op.create_index(op.f('ix_blog_home_page_updated_by'), 'blog_home_page', ['updated_by'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_created_by'), 'category', ['created_by'], unique=False)
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_is_active'), 'category', ['is_active'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.create_index(op.f('ix_category_updated_by'), 'category', ['updated_by'], unique=False)
    op.create_table('footer_website',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('icon_img', sa.String(length=100), nullable=True),
    sa.Column('link_ref', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_footer_website_created_by'), 'footer_website', ['created_by'], unique=False)
    op.create_index(op.f('ix_footer_website_id'), 'footer_website', ['id'], unique=False)
    op.create_index(op.f('ix_footer_website_is_active'), 'footer_website', ['is_active'], unique=False)
    op.create_index(op.f('ix_footer_website_title'), 'footer_website', ['title'], unique=False)
    op.create_index(op.f('ix_footer_website_updated_by'), 'footer_website', ['updated_by'], unique=False)
    op.create_table('order_type',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('type_name', sa.String(length=150), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_type_created_by'), 'order_type', ['created_by'], unique=False)
    op.create_index(op.f('ix_order_type_id'), 'order_type', ['id'], unique=False)
    op.create_index(op.f('ix_order_type_is_active'), 'order_type', ['is_active'], unique=False)
    op.create_index(op.f('ix_order_type_type_name'), 'order_type', ['type_name'], unique=False)
    op.create_index(op.f('ix_order_type_updated_by'), 'order_type', ['updated_by'], unique=False)
    op.create_table('promotions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('promocode', sa.String(length=50), nullable=True),
    sa.Column('promotion_title', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_created_by'), 'promotions', ['created_by'], unique=False)
    op.create_index(op.f('ix_promotions_id'), 'promotions', ['id'], unique=False)
    op.create_index(op.f('ix_promotions_is_active'), 'promotions', ['is_active'], unique=False)
    op.create_index(op.f('ix_promotions_promocode'), 'promotions', ['promocode'], unique=False)
    op.create_index(op.f('ix_promotions_updated_by'), 'promotions', ['updated_by'], unique=False)
    op.create_table('ref_zone',
    sa.Column('ZoneId', sa.Integer(), nullable=False),
    sa.Column('ZoneNameTH', sa.String(length=50), nullable=True),
    sa.Column('ZoneNameEN', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ZoneId')
    )
    op.create_index(op.f('ix_ref_zone_ZoneId'), 'ref_zone', ['ZoneId'], unique=False)
    op.create_index(op.f('ix_ref_zone_ZoneNameEN'), 'ref_zone', ['ZoneNameEN'], unique=False)
    op.create_index(op.f('ix_ref_zone_ZoneNameTH'), 'ref_zone', ['ZoneNameTH'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_created_by'), 'role', ['created_by'], unique=False)
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_is_active'), 'role', ['is_active'], unique=False)
    op.create_index(op.f('ix_role_role_name'), 'role', ['role_name'], unique=False)
    op.create_index(op.f('ix_role_updated_by'), 'role', ['updated_by'], unique=False)
    op.create_table('slide_activity',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('img_file_name', sa.String(length=150), nullable=True),
    sa.Column('img_path', sa.String(length=150), nullable=True),
    sa.Column('like', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slide_activity_created_by'), 'slide_activity', ['created_by'], unique=False)
    op.create_index(op.f('ix_slide_activity_id'), 'slide_activity', ['id'], unique=False)
    op.create_index(op.f('ix_slide_activity_is_active'), 'slide_activity', ['is_active'], unique=False)
    op.create_index(op.f('ix_slide_activity_title'), 'slide_activity', ['title'], unique=False)
    op.create_index(op.f('ix_slide_activity_updated_by'), 'slide_activity', ['updated_by'], unique=False)
    op.create_table('slide_news',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('link_ref', sa.String(length=100), nullable=True),
    sa.Column('img_path', sa.String(length=200), nullable=True),
    sa.Column('slide_number', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slide_news_created_by'), 'slide_news', ['created_by'], unique=False)
    op.create_index(op.f('ix_slide_news_id'), 'slide_news', ['id'], unique=False)
    op.create_index(op.f('ix_slide_news_is_active'), 'slide_news', ['is_active'], unique=False)
    op.create_index(op.f('ix_slide_news_title'), 'slide_news', ['title'], unique=False)
    op.create_index(op.f('ix_slide_news_updated_by'), 'slide_news', ['updated_by'], unique=False)
    op.create_table('blog',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('cover_img', sa.String(length=150), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('view', sa.Integer(), nullable=True),
    sa.Column('like', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_category_id'), 'blog', ['category_id'], unique=False)
    op.create_index(op.f('ix_blog_created_by'), 'blog', ['created_by'], unique=False)
    op.create_index(op.f('ix_blog_id'), 'blog', ['id'], unique=False)
    op.create_index(op.f('ix_blog_is_active'), 'blog', ['is_active'], unique=False)
    op.create_index(op.f('ix_blog_updated_by'), 'blog', ['updated_by'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('emphasize_particular', sa.String(length=150), nullable=True),
    sa.Column('supplement', sa.String(length=150), nullable=True),
    sa.Column('supplement_other', sa.String(length=150), nullable=True),
    sa.Column('birth_date_idol', sa.Date(), nullable=True),
    sa.Column('services_zodiac', sa.Boolean(), nullable=True),
    sa.Column('services_auspicious', sa.Boolean(), nullable=True),
    sa.Column('first_name_customer', sa.String(length=150), nullable=True),
    sa.Column('last_name_customer', sa.String(length=150), nullable=True),
    sa.Column('birth_date_customer', sa.Date(), nullable=True),
    sa.Column('birth_time_customer', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=100), nullable=True),
    sa.Column('lgbt_description', sa.String(length=255), nullable=True),
    sa.Column('congenital_disease', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('newsletter', sa.Boolean(), nullable=True),
    sa.Column('read_accept_pdpa', sa.Boolean(), nullable=True),
    sa.Column('promotion_id', sa.String(length=50), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('send_wallpaper_status', sa.String(length=20), nullable=True),
    sa.Column('order_type_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['order_type_id'], ['order_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_created_by'), 'order', ['created_by'], unique=False)
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_index(op.f('ix_order_is_active'), 'order', ['is_active'], unique=False)
    op.create_index(op.f('ix_order_order_type_id'), 'order', ['order_type_id'], unique=False)
    op.create_index(op.f('ix_order_updated_by'), 'order', ['updated_by'], unique=False)
    op.create_table('ref_provinces',
    sa.Column('ProvinceId', sa.Integer(), nullable=False),
    sa.Column('ProvinceNameTH', sa.String(length=50), nullable=True),
    sa.Column('ProvinceNameEN', sa.String(length=50), nullable=True),
    sa.Column('ZoneId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ZoneId'], ['ref_zone.ZoneId'], ),
    sa.PrimaryKeyConstraint('ProvinceId')
    )
    op.create_index(op.f('ix_ref_provinces_ProvinceId'), 'ref_provinces', ['ProvinceId'], unique=False)
    op.create_index(op.f('ix_ref_provinces_ProvinceNameEN'), 'ref_provinces', ['ProvinceNameEN'], unique=False)
    op.create_index(op.f('ix_ref_provinces_ProvinceNameTH'), 'ref_provinces', ['ProvinceNameTH'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('f_name', sa.String(length=100), nullable=True),
    sa.Column('l_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('img_profile', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('keep_following', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_address'), 'user', ['address'], unique=False)
    op.create_index(op.f('ix_user_created_by'), 'user', ['created_by'], unique=False)
    op.create_index(op.f('ix_user_f_name'), 'user', ['f_name'], unique=False)
    op.create_index(op.f('ix_user_following'), 'user', ['following'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_img_profile'), 'user', ['img_profile'], unique=False)
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_keep_following'), 'user', ['keep_following'], unique=False)
    op.create_index(op.f('ix_user_l_name'), 'user', ['l_name'], unique=False)
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    op.create_index(op.f('ix_user_updated_by'), 'user', ['updated_by'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_updated_by'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_index(op.f('ix_user_l_name'), table_name='user')
    op.drop_index(op.f('ix_user_keep_following'), table_name='user')
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_index(op.f('ix_user_img_profile'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_following'), table_name='user')
    op.drop_index(op.f('ix_user_f_name'), table_name='user')
    op.drop_index(op.f('ix_user_created_by'), table_name='user')
    op.drop_index(op.f('ix_user_address'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_ref_provinces_ProvinceNameTH'), table_name='ref_provinces')
    op.drop_index(op.f('ix_ref_provinces_ProvinceNameEN'), table_name='ref_provinces')
    op.drop_index(op.f('ix_ref_provinces_ProvinceId'), table_name='ref_provinces')
    op.drop_table('ref_provinces')
    op.drop_index(op.f('ix_order_updated_by'), table_name='order')
    op.drop_index(op.f('ix_order_order_type_id'), table_name='order')
    op.drop_index(op.f('ix_order_is_active'), table_name='order')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_index(op.f('ix_order_created_by'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_blog_updated_by'), table_name='blog')
    op.drop_index(op.f('ix_blog_is_active'), table_name='blog')
    op.drop_index(op.f('ix_blog_id'), table_name='blog')
    op.drop_index(op.f('ix_blog_created_by'), table_name='blog')
    op.drop_index(op.f('ix_blog_category_id'), table_name='blog')
    op.drop_table('blog')
    op.drop_index(op.f('ix_slide_news_updated_by'), table_name='slide_news')
    op.drop_index(op.f('ix_slide_news_title'), table_name='slide_news')
    op.drop_index(op.f('ix_slide_news_is_active'), table_name='slide_news')
    op.drop_index(op.f('ix_slide_news_id'), table_name='slide_news')
    op.drop_index(op.f('ix_slide_news_created_by'), table_name='slide_news')
    op.drop_table('slide_news')
    op.drop_index(op.f('ix_slide_activity_updated_by'), table_name='slide_activity')
    op.drop_index(op.f('ix_slide_activity_title'), table_name='slide_activity')
    op.drop_index(op.f('ix_slide_activity_is_active'), table_name='slide_activity')
    op.drop_index(op.f('ix_slide_activity_id'), table_name='slide_activity')
    op.drop_index(op.f('ix_slide_activity_created_by'), table_name='slide_activity')
    op.drop_table('slide_activity')
    op.drop_index(op.f('ix_role_updated_by'), table_name='role')
    op.drop_index(op.f('ix_role_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_is_active'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_index(op.f('ix_role_created_by'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_ref_zone_ZoneNameTH'), table_name='ref_zone')
    op.drop_index(op.f('ix_ref_zone_ZoneNameEN'), table_name='ref_zone')
    op.drop_index(op.f('ix_ref_zone_ZoneId'), table_name='ref_zone')
    op.drop_table('ref_zone')
    op.drop_index(op.f('ix_promotions_updated_by'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_promocode'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_is_active'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_id'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_created_by'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_order_type_updated_by'), table_name='order_type')
    op.drop_index(op.f('ix_order_type_type_name'), table_name='order_type')
    op.drop_index(op.f('ix_order_type_is_active'), table_name='order_type')
    op.drop_index(op.f('ix_order_type_id'), table_name='order_type')
    op.drop_index(op.f('ix_order_type_created_by'), table_name='order_type')
    op.drop_table('order_type')
    op.drop_index(op.f('ix_footer_website_updated_by'), table_name='footer_website')
    op.drop_index(op.f('ix_footer_website_title'), table_name='footer_website')
    op.drop_index(op.f('ix_footer_website_is_active'), table_name='footer_website')
    op.drop_index(op.f('ix_footer_website_id'), table_name='footer_website')
    op.drop_index(op.f('ix_footer_website_created_by'), table_name='footer_website')
    op.drop_table('footer_website')
    op.drop_index(op.f('ix_category_updated_by'), table_name='category')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_is_active'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_index(op.f('ix_category_created_by'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_blog_home_page_updated_by'), table_name='blog_home_page')
    op.drop_index(op.f('ix_blog_home_page_is_active'), table_name='blog_home_page')
    op.drop_index(op.f('ix_blog_home_page_id'), table_name='blog_home_page')
    op.drop_index(op.f('ix_blog_home_page_created_by'), table_name='blog_home_page')
    op.drop_table('blog_home_page')
    # ### end Alembic commands ###
