"""update order

Revision ID: 7a7f1631c632
Revises: d37b556c68b4
Create Date: 2025-12-30 12:54:24.345720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7f1631c632'
down_revision: Union[str, Sequence[str], None] = 'd37b556c68b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('wallpaper_url', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_order_birth_date_customer'), table_name='order')
    op.drop_index(op.f('ix_order_birth_month_customer'), table_name='order')
    op.drop_index(op.f('ix_order_promotion_id'), table_name='order')
    op.drop_index(op.f('ix_order_zodiac_customer'), table_name='order')
    op.drop_constraint(op.f('order_promotion_id_fkey'), 'order', type_='foreignkey')
    op.drop_column('order', 'send_wallpaper_status')
    op.drop_column('order', 'promotion_id')
    op.drop_column('order', 'is_active')
    op.drop_column('order', 'congenital_disease')
    op.drop_column('order', 'zodiac_customer')
    op.drop_column('order', 'gender')
    op.drop_column('order', 'birth_month_customer')
    op.drop_column('order', 'note')
    op.drop_column('order', 'birth_date_customer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('birth_date_customer', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('note', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('birth_month_customer', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('gender', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('zodiac_customer', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('congenital_disease', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('promotion_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('send_wallpaper_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('order_promotion_id_fkey'), 'order', 'promotions', ['promotion_id'], ['id'])
    op.create_index(op.f('ix_order_zodiac_customer'), 'order', ['zodiac_customer'], unique=False)
    op.create_index(op.f('ix_order_promotion_id'), 'order', ['promotion_id'], unique=False)
    op.create_index(op.f('ix_order_birth_month_customer'), 'order', ['birth_month_customer'], unique=False)
    op.create_index(op.f('ix_order_birth_date_customer'), 'order', ['birth_date_customer'], unique=False)
    op.drop_column('order', 'wallpaper_url')
    # ### end Alembic commands ###
