"""order type key nullable

Revision ID: 969bcee2f747
Revises: 443da6f40954
Create Date: 2025-12-31 03:56:27.663633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '969bcee2f747'
down_revision: Union[str, Sequence[str], None] = '443da6f40954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_type', sa.Column('key', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_order_type_key'), 'order_type', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_type_key'), table_name='order_type')
    op.drop_column('order_type', 'key')
    # ### end Alembic commands ###
