"""create tables

Revision ID: 13b185644a91
Revises: 5f693a2ea0a9
Create Date: 2025-09-20 19:56:26.565736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b185644a91'
down_revision: Union[str, Sequence[str], None] = '5f693a2ea0a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mtw_orders_type', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mtw_orders_type', 'price')
    # ### end Alembic commands ###
