"""migration mtw_footer_website

Revision ID: 13b50c9eb68b
Revises: 3639b6481b6e
Create Date: 2025-09-26 22:00:27.321839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b50c9eb68b'
down_revision: Union[str, Sequence[str], None] = '3639b6481b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mtw_footer_website',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('icon_img', sa.String(length=100), nullable=True),
    sa.Column('link_ref', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mtw_footer_website_created_by'), 'mtw_footer_website', ['created_by'], unique=False)
    op.create_index(op.f('ix_mtw_footer_website_id'), 'mtw_footer_website', ['id'], unique=False)
    op.create_index(op.f('ix_mtw_footer_website_is_active'), 'mtw_footer_website', ['is_active'], unique=False)
    op.create_index(op.f('ix_mtw_footer_website_title'), 'mtw_footer_website', ['title'], unique=False)
    op.create_index(op.f('ix_mtw_footer_website_updated_by'), 'mtw_footer_website', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mtw_footer_website_updated_by'), table_name='mtw_footer_website')
    op.drop_index(op.f('ix_mtw_footer_website_title'), table_name='mtw_footer_website')
    op.drop_index(op.f('ix_mtw_footer_website_is_active'), table_name='mtw_footer_website')
    op.drop_index(op.f('ix_mtw_footer_website_id'), table_name='mtw_footer_website')
    op.drop_index(op.f('ix_mtw_footer_website_created_by'), table_name='mtw_footer_website')
    op.drop_table('mtw_footer_website')
    # ### end Alembic commands ###
