"""add slide activity new

Revision ID: 29219f453513
Revises: 6bb0adfa7b2f
Create Date: 2025-09-26 22:50:41.477333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29219f453513'
down_revision: Union[str, Sequence[str], None] = '6bb0adfa7b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mtw_slide_activity',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('img_file_name', sa.String(length=150), nullable=True),
    sa.Column('img_path', sa.String(length=150), nullable=True),
    sa.Column('like', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mtw_slide_activity_created_by'), 'mtw_slide_activity', ['created_by'], unique=False)
    op.create_index(op.f('ix_mtw_slide_activity_id'), 'mtw_slide_activity', ['id'], unique=False)
    op.create_index(op.f('ix_mtw_slide_activity_is_active'), 'mtw_slide_activity', ['is_active'], unique=False)
    op.create_index(op.f('ix_mtw_slide_activity_title'), 'mtw_slide_activity', ['title'], unique=False)
    op.create_index(op.f('ix_mtw_slide_activity_updated_by'), 'mtw_slide_activity', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mtw_slide_activity_updated_by'), table_name='mtw_slide_activity')
    op.drop_index(op.f('ix_mtw_slide_activity_title'), table_name='mtw_slide_activity')
    op.drop_index(op.f('ix_mtw_slide_activity_is_active'), table_name='mtw_slide_activity')
    op.drop_index(op.f('ix_mtw_slide_activity_id'), table_name='mtw_slide_activity')
    op.drop_index(op.f('ix_mtw_slide_activity_created_by'), table_name='mtw_slide_activity')
    op.drop_table('mtw_slide_activity')
    # ### end Alembic commands ###
