"""create tables

Revision ID: 50408e87bee2
Revises: 13b185644a91
Create Date: 2025-09-20 20:42:15.061124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50408e87bee2'
down_revision: Union[str, Sequence[str], None] = '13b185644a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mtw_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('f_name', sa.String(length=100), nullable=True),
    sa.Column('l_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('img_profile', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('keep_following', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['mtw_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mtw_users_address'), 'mtw_users', ['address'], unique=False)
    op.create_index(op.f('ix_mtw_users_created_by'), 'mtw_users', ['created_by'], unique=False)
    op.create_index(op.f('ix_mtw_users_f_name'), 'mtw_users', ['f_name'], unique=False)
    op.create_index(op.f('ix_mtw_users_following'), 'mtw_users', ['following'], unique=False)
    op.create_index(op.f('ix_mtw_users_id'), 'mtw_users', ['id'], unique=False)
    op.create_index(op.f('ix_mtw_users_img_profile'), 'mtw_users', ['img_profile'], unique=False)
    op.create_index(op.f('ix_mtw_users_is_active'), 'mtw_users', ['is_active'], unique=False)
    op.create_index(op.f('ix_mtw_users_keep_following'), 'mtw_users', ['keep_following'], unique=False)
    op.create_index(op.f('ix_mtw_users_l_name'), 'mtw_users', ['l_name'], unique=False)
    op.create_index(op.f('ix_mtw_users_password'), 'mtw_users', ['password'], unique=False)
    op.create_index(op.f('ix_mtw_users_phone'), 'mtw_users', ['phone'], unique=False)
    op.create_index(op.f('ix_mtw_users_updated_by'), 'mtw_users', ['updated_by'], unique=False)
    op.create_index(op.f('ix_mtw_users_username'), 'mtw_users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mtw_users_username'), table_name='mtw_users')
    op.drop_index(op.f('ix_mtw_users_updated_by'), table_name='mtw_users')
    op.drop_index(op.f('ix_mtw_users_phone'), table_name='mtw_users')
    op.drop_index(op.f('ix_mtw_users_password'), table_name='mtw_users')
    op.drop_index(op.f('ix_mtw_users_l_name'), table_name='mtw_users')
    op.drop_index(op.f('ix_mtw_users_keep_following'), table_name='mtw_users')
    op.drop_index(op.f('ix_mtw_users_is_active'), table_name='mtw_users')
    op.drop_index(op.f('ix_mtw_users_img_profile'), table_name='mtw_users')
    op.drop_index(op.f('ix_mtw_users_id'), table_name='mtw_users')
    op.drop_index(op.f('ix_mtw_users_following'), table_name='mtw_users')
    op.drop_index(op.f('ix_mtw_users_f_name'), table_name='mtw_users')
    op.drop_index(op.f('ix_mtw_users_created_by'), table_name='mtw_users')
    op.drop_index(op.f('ix_mtw_users_address'), table_name='mtw_users')
    op.drop_table('mtw_users')
    # ### end Alembic commands ###
