"""create tables

Revision ID: 61d01e0f147a
Revises: 
Create Date: 2025-09-20 19:16:58.687637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d01e0f147a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mtw_orders_type',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('type_name', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mtw_orders_type_created_by'), 'mtw_orders_type', ['created_by'], unique=False)
    op.create_index(op.f('ix_mtw_orders_type_id'), 'mtw_orders_type', ['id'], unique=False)
    op.create_index(op.f('ix_mtw_orders_type_is_active'), 'mtw_orders_type', ['is_active'], unique=False)
    op.create_index(op.f('ix_mtw_orders_type_type_name'), 'mtw_orders_type', ['type_name'], unique=False)
    op.create_index(op.f('ix_mtw_orders_type_updated_by'), 'mtw_orders_type', ['updated_by'], unique=False)
    op.create_table('mtw_promotion',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('promocode', sa.String(length=50), nullable=True),
    sa.Column('promotion_title', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mtw_promotion_created_by'), 'mtw_promotion', ['created_by'], unique=False)
    op.create_index(op.f('ix_mtw_promotion_id'), 'mtw_promotion', ['id'], unique=False)
    op.create_index(op.f('ix_mtw_promotion_is_active'), 'mtw_promotion', ['is_active'], unique=False)
    op.create_index(op.f('ix_mtw_promotion_promocode'), 'mtw_promotion', ['promocode'], unique=False)
    op.create_index(op.f('ix_mtw_promotion_updated_by'), 'mtw_promotion', ['updated_by'], unique=False)
    op.create_table('mtw_role',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mtw_role_created_by'), 'mtw_role', ['created_by'], unique=False)
    op.create_index(op.f('ix_mtw_role_id'), 'mtw_role', ['id'], unique=False)
    op.create_index(op.f('ix_mtw_role_is_active'), 'mtw_role', ['is_active'], unique=False)
    op.create_index(op.f('ix_mtw_role_role_name'), 'mtw_role', ['role_name'], unique=False)
    op.create_index(op.f('ix_mtw_role_updated_by'), 'mtw_role', ['updated_by'], unique=False)
    op.create_table('ref_zone',
    sa.Column('ZoneId', sa.Integer(), nullable=False),
    sa.Column('ZoneNameTH', sa.String(length=50), nullable=True),
    sa.Column('ZoneNameEN', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ZoneId')
    )
    op.create_index(op.f('ix_ref_zone_ZoneId'), 'ref_zone', ['ZoneId'], unique=False)
    op.create_index(op.f('ix_ref_zone_ZoneNameEN'), 'ref_zone', ['ZoneNameEN'], unique=False)
    op.create_index(op.f('ix_ref_zone_ZoneNameTH'), 'ref_zone', ['ZoneNameTH'], unique=False)
    op.create_table('mtw_orders',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('order_type_id', sa.String(length=50), nullable=True),
    sa.Column('emphasize_particular', sa.String(length=150), nullable=True),
    sa.Column('supplement', sa.String(length=150), nullable=True),
    sa.Column('supplement_other', sa.String(length=150), nullable=True),
    sa.Column('birth_date_idol', sa.Date(), nullable=True),
    sa.Column('services_zodiac', sa.Boolean(), nullable=True),
    sa.Column('services_auspicious', sa.Boolean(), nullable=True),
    sa.Column('frist_name_customer', sa.String(length=150), nullable=True),
    sa.Column('last_name_customer', sa.String(length=150), nullable=True),
    sa.Column('birth_date_customer', sa.Date(), nullable=True),
    sa.Column('birth_time_customer', sa.String(length=20), nullable=True),
    sa.Column('gendor', sa.String(length=100), nullable=True),
    sa.Column('lgbt_description', sa.String(length=255), nullable=True),
    sa.Column('congenital_disease', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('newsletter', sa.Boolean(), nullable=True),
    sa.Column('read_accept_pdpa', sa.Boolean(), nullable=True),
    sa.Column('promotion_id', sa.String(length=50), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('send_wallpaer_status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['order_type_id'], ['mtw_orders_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mtw_orders_created_by'), 'mtw_orders', ['created_by'], unique=False)
    op.create_index(op.f('ix_mtw_orders_id'), 'mtw_orders', ['id'], unique=False)
    op.create_index(op.f('ix_mtw_orders_is_active'), 'mtw_orders', ['is_active'], unique=False)
    op.create_index(op.f('ix_mtw_orders_order_type_id'), 'mtw_orders', ['order_type_id'], unique=False)
    op.create_index(op.f('ix_mtw_orders_updated_by'), 'mtw_orders', ['updated_by'], unique=False)
    op.create_table('ref_provinces',
    sa.Column('ProvinceId', sa.Integer(), nullable=False),
    sa.Column('ProvinceNameTH', sa.String(length=50), nullable=True),
    sa.Column('ProvinceNameEN', sa.String(length=50), nullable=True),
    sa.Column('ZoneId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ZoneId'], ['ref_zone.ZoneId'], ),
    sa.PrimaryKeyConstraint('ProvinceId')
    )
    op.create_index(op.f('ix_ref_provinces_ProvinceId'), 'ref_provinces', ['ProvinceId'], unique=False)
    op.create_index(op.f('ix_ref_provinces_ProvinceNameEN'), 'ref_provinces', ['ProvinceNameEN'], unique=False)
    op.create_index(op.f('ix_ref_provinces_ProvinceNameTH'), 'ref_provinces', ['ProvinceNameTH'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ref_provinces_ProvinceNameTH'), table_name='ref_provinces')
    op.drop_index(op.f('ix_ref_provinces_ProvinceNameEN'), table_name='ref_provinces')
    op.drop_index(op.f('ix_ref_provinces_ProvinceId'), table_name='ref_provinces')
    op.drop_table('ref_provinces')
    op.drop_index(op.f('ix_mtw_orders_updated_by'), table_name='mtw_orders')
    op.drop_index(op.f('ix_mtw_orders_order_type_id'), table_name='mtw_orders')
    op.drop_index(op.f('ix_mtw_orders_is_active'), table_name='mtw_orders')
    op.drop_index(op.f('ix_mtw_orders_id'), table_name='mtw_orders')
    op.drop_index(op.f('ix_mtw_orders_created_by'), table_name='mtw_orders')
    op.drop_table('mtw_orders')
    op.drop_index(op.f('ix_ref_zone_ZoneNameTH'), table_name='ref_zone')
    op.drop_index(op.f('ix_ref_zone_ZoneNameEN'), table_name='ref_zone')
    op.drop_index(op.f('ix_ref_zone_ZoneId'), table_name='ref_zone')
    op.drop_table('ref_zone')
    op.drop_index(op.f('ix_mtw_role_updated_by'), table_name='mtw_role')
    op.drop_index(op.f('ix_mtw_role_role_name'), table_name='mtw_role')
    op.drop_index(op.f('ix_mtw_role_is_active'), table_name='mtw_role')
    op.drop_index(op.f('ix_mtw_role_id'), table_name='mtw_role')
    op.drop_index(op.f('ix_mtw_role_created_by'), table_name='mtw_role')
    op.drop_table('mtw_role')
    op.drop_index(op.f('ix_mtw_promotion_updated_by'), table_name='mtw_promotion')
    op.drop_index(op.f('ix_mtw_promotion_promocode'), table_name='mtw_promotion')
    op.drop_index(op.f('ix_mtw_promotion_is_active'), table_name='mtw_promotion')
    op.drop_index(op.f('ix_mtw_promotion_id'), table_name='mtw_promotion')
    op.drop_index(op.f('ix_mtw_promotion_created_by'), table_name='mtw_promotion')
    op.drop_table('mtw_promotion')
    op.drop_index(op.f('ix_mtw_orders_type_updated_by'), table_name='mtw_orders_type')
    op.drop_index(op.f('ix_mtw_orders_type_type_name'), table_name='mtw_orders_type')
    op.drop_index(op.f('ix_mtw_orders_type_is_active'), table_name='mtw_orders_type')
    op.drop_index(op.f('ix_mtw_orders_type_id'), table_name='mtw_orders_type')
    op.drop_index(op.f('ix_mtw_orders_type_created_by'), table_name='mtw_orders_type')
    op.drop_table('mtw_orders_type')
    # ### end Alembic commands ###
