"""message

Revision ID: 7905f74985e1
Revises: 3a5dc605c203
Create Date: 2025-09-25 23:14:40.792943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7905f74985e1'
down_revision: Union[str, Sequence[str], None] = '3a5dc605c203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mtw_blog_home_page',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('blog_title', sa.String(length=200), nullable=True),
    sa.Column('blog_note', sa.String(length=150), nullable=True),
    sa.Column('blog_img_path', sa.String(length=150), nullable=True),
    sa.Column('blog_link', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mtw_blog_home_page_created_by'), 'mtw_blog_home_page', ['created_by'], unique=False)
    op.create_index(op.f('ix_mtw_blog_home_page_id'), 'mtw_blog_home_page', ['id'], unique=False)
    op.create_index(op.f('ix_mtw_blog_home_page_is_active'), 'mtw_blog_home_page', ['is_active'], unique=False)
    op.create_index(op.f('ix_mtw_blog_home_page_updated_by'), 'mtw_blog_home_page', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mtw_blog_home_page_updated_by'), table_name='mtw_blog_home_page')
    op.drop_index(op.f('ix_mtw_blog_home_page_is_active'), table_name='mtw_blog_home_page')
    op.drop_index(op.f('ix_mtw_blog_home_page_id'), table_name='mtw_blog_home_page')
    op.drop_index(op.f('ix_mtw_blog_home_page_created_by'), table_name='mtw_blog_home_page')
    op.drop_table('mtw_blog_home_page')
    # ### end Alembic commands ###
