"""create tables

Revision ID: d294a58de913
Revises: 321beefe5619
Create Date: 2025-09-21 00:18:38.597270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd294a58de913'
down_revision: Union[str, Sequence[str], None] = '321beefe5619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mtw_article_categories',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mtw_article_categories_created_by'), 'mtw_article_categories', ['created_by'], unique=False)
    op.create_index(op.f('ix_mtw_article_categories_id'), 'mtw_article_categories', ['id'], unique=False)
    op.create_index(op.f('ix_mtw_article_categories_is_active'), 'mtw_article_categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_mtw_article_categories_updated_by'), 'mtw_article_categories', ['updated_by'], unique=False)
    op.create_table('mtw_slide_new',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('link_ref', sa.String(length=100), nullable=True),
    sa.Column('img_path', sa.String(length=200), nullable=True),
    sa.Column('slide_number', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mtw_slide_new_created_by'), 'mtw_slide_new', ['created_by'], unique=False)
    op.create_index(op.f('ix_mtw_slide_new_id'), 'mtw_slide_new', ['id'], unique=False)
    op.create_index(op.f('ix_mtw_slide_new_is_active'), 'mtw_slide_new', ['is_active'], unique=False)
    op.create_index(op.f('ix_mtw_slide_new_title'), 'mtw_slide_new', ['title'], unique=False)
    op.create_index(op.f('ix_mtw_slide_new_updated_by'), 'mtw_slide_new', ['updated_by'], unique=False)
    op.create_table('mtw_aticle_blog',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('cover_img', sa.String(length=150), nullable=True),
    sa.Column('conten', sa.Text(), nullable=True),
    sa.Column('view', sa.Integer(), nullable=True),
    sa.Column('like', sa.Integer(), nullable=True),
    sa.Column('article_categories_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['article_categories_id'], ['mtw_article_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mtw_aticle_blog_article_categories_id'), 'mtw_aticle_blog', ['article_categories_id'], unique=False)
    op.create_index(op.f('ix_mtw_aticle_blog_created_by'), 'mtw_aticle_blog', ['created_by'], unique=False)
    op.create_index(op.f('ix_mtw_aticle_blog_id'), 'mtw_aticle_blog', ['id'], unique=False)
    op.create_index(op.f('ix_mtw_aticle_blog_is_active'), 'mtw_aticle_blog', ['is_active'], unique=False)
    op.create_index(op.f('ix_mtw_aticle_blog_updated_by'), 'mtw_aticle_blog', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mtw_aticle_blog_updated_by'), table_name='mtw_aticle_blog')
    op.drop_index(op.f('ix_mtw_aticle_blog_is_active'), table_name='mtw_aticle_blog')
    op.drop_index(op.f('ix_mtw_aticle_blog_id'), table_name='mtw_aticle_blog')
    op.drop_index(op.f('ix_mtw_aticle_blog_created_by'), table_name='mtw_aticle_blog')
    op.drop_index(op.f('ix_mtw_aticle_blog_article_categories_id'), table_name='mtw_aticle_blog')
    op.drop_table('mtw_aticle_blog')
    op.drop_index(op.f('ix_mtw_slide_new_updated_by'), table_name='mtw_slide_new')
    op.drop_index(op.f('ix_mtw_slide_new_title'), table_name='mtw_slide_new')
    op.drop_index(op.f('ix_mtw_slide_new_is_active'), table_name='mtw_slide_new')
    op.drop_index(op.f('ix_mtw_slide_new_id'), table_name='mtw_slide_new')
    op.drop_index(op.f('ix_mtw_slide_new_created_by'), table_name='mtw_slide_new')
    op.drop_table('mtw_slide_new')
    op.drop_index(op.f('ix_mtw_article_categories_updated_by'), table_name='mtw_article_categories')
    op.drop_index(op.f('ix_mtw_article_categories_is_active'), table_name='mtw_article_categories')
    op.drop_index(op.f('ix_mtw_article_categories_id'), table_name='mtw_article_categories')
    op.drop_index(op.f('ix_mtw_article_categories_created_by'), table_name='mtw_article_categories')
    op.drop_table('mtw_article_categories')
    # ### end Alembic commands ###
